### ISSUE TITLE
Failed to find battleye init function 

### ISSUE THREAD

**Issue by Cy63rfury** [JonathanEke/DayZ-Server-Battleye-Remover#3]
When I exexute the patch I get the following error:

Created backup.
Failed to find battleye init function.
Press any key to continue . . .

I'm in the right folder
Using DayZServer_x64.exe version 1.25.199 )15.2 MB (15,989,240 bytes)
Filedate created    :  ‎20 ‎November ‎2024, ‏‎13:54:35
Filedate modified :  29 ‎May ‎2024, ‏‎05:02:41     
Last Accessed       : ‎Today, ‎2 ‎December ‎2024, ‏‎1 minute ago

This script was created for another version? How to proceed

**Comment by Cy63rfury** [comment]
[Uploading DayZServer_x64.zip…]()

**Comment by Sin213** [comment]
Same error

**Comment by JonathanEke** [comment]
I have tested on the latest version of dayz server and is working fine.
make sure you are using the latest release i posted here in October.
